export const allTroops = [
  "barbarian",
  "s-barbarian",
  "archer",
  "s-archer",
  "giant",
  "s-giant",
  "goblin",
  "s-goblin",
  "wallbreaker",
  "s-wallbreaker",
  "balloon",
  "r-balloon",
  "wizard",
  "s-wizard",
  "healer",
  "dragon",
  "s-dragon",
  "PEKKA",
  "b-dragon",
  "i-dragon",
  "miner",
  "s-miner",
  "e-dragon",
  "yeti",
  "dragonrider",
  "e-titan",
  "minion",
  "s-minion",
  "hogrider",
  "s-hogrider",
  "valkyrie",
  "s-valkyrie",
  "golem",
  "witch",
  "s-witch",
  "lavahound",
  "icehound",
  "bowler",
  "s-bowler",
  "icegolem",
  "headhunter",
  "apprenticewarden",
];

export const allSpells = [
  'lightning', 
  'heal', 
  'rage', 
  'jump', 
  'freeze', 
  'clone', 
  'invisibility', 
  'recall',
  'poison', 
  'earthquake', 
  'haste', 
  'skeleton', 
  'bat'
];

export const allSieges = [
  'wall-wrecker', 
  'battle-blimp', 
  'stone-slammer', 
  'siege-barracks', 
  'log-launcher',
  'flame-flinger', 
  'battle-drill'
];

export const statIcons = { 'hp': "/src/assets/icons/stat_icons/hp.png",
                      'heal1': "src/assets/icons/stat_icons/heal_troop.png",
                      'heal2': "src/assets/icons/stat_icons/heal_hero.png",
                      'damage': "/src/assets/icons/stat_icons/damage.png",
                      'speed': "/src/assets/icons/stat_icons/speed.png",
                      'time': "/src/assets/icons/stopwatch.png",
                      'housing': "/src/assets/icons/stat_icons/troop_silhouette.png",
                      'target': "/src/assets/icons/stat_icons/target.png",
                      'poison': "/src/assets/icons/stat_icons/poison.png",
                      'count': "/src/assets/icons/stat_icons/count.png"
                    }